version: "3.1"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro    
    networks:
      - chancalay-network

  chancalay:
    image: nginx:1.17
    container_name: nginx-chancalay
    restart: always
    environment:
      - VIRTUAL_HOST=chancalay.com
    expose:
      - "80"
    volumes:
      - ./www/chancalay:/usr/share/nginx/html
      - ./logs:/var/log/nginx
    networks:
      - chancalay-network  
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: php74
    ports:
      - 9000:9000
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./logs:/var/log/nginx
    networks:
      - chancalay-network

networks:
  chancalay-network:
    external: true