version: '3'

services:

  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy # Es un nginx que permite redireccionar el tráfico hacia otros contenedores
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro # Monta el socket de Docker para mantener actualizada la configuración de los vhosts de los contenedores que se ejecutan o detienen.
      - ./nginx/acme:/etc/acme.sh # Directorio para almacenar los archivos y configuraciones de acme.sh
      - ./nginx/certs:/etc/nginx/certs:ro # Directorio para almacenar los certificados SSL/TLS
      - ./nginx/html:/usr/share/nginx/html # Directorio para que LetsEncrypt pueda escribir los archivos de validación
      - ./nginx/vhostd:/etc/nginx/vhost.d # Directorio para que LetsEncrypt pueda escribir en los vhosts
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy # Requerido según la documentación

  letsencrypt:
    container_name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion # es como un compañero para el nginx-proxy. Se encarga de generar y administrar los certificados SSL mediante Let's Encrypt para los dominios configurados en los otros servicios.
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Monta el socket de Docker para permitir la comunicación con el contenedor nginx-proxy
      - ./nginx/acme:/etc/acme.sh # Monta el directorio para los archivos y configuraciones de acme.sh
      - ./nginx/certs:/etc/nginx/certs:rw # Monta el directorio para los certificados SSL/TLS
      - ./nginx/html:/usr/share/nginx/html # Monta el directorio para que LetsEncrypt pueda escribir los archivos de validación
      - ./nginx/vhostd:/etc/nginx/vhost.d # Monta el directorio para que LetsEncrypt pueda escribir en los vhosts

  www:
    container_name: www
    image: nginx:1.17
    restart: always
    ports:
      - "80:80" # Expone el puerto en forma interna solo para la red de Docker ('expose' en vez de 'ports')
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html # Monta el directorio con los archivos del sitio web en el contenedor nginx
      - ./logs:/var/log/nginx
    environment:
      - VIRTUAL_HOST=local.chancalay.com # Los vhosts (separados por coma)
      - LETSENCRYPT_HOST=local.chancalay.com # Los dominios a certificar (separados por coma)
      - LETSENCRYPT_EMAIL=cachoalbornoz@gmail.com # Email para validación / notificaciones  
    networks:
      - nginx-proxy   
    links:
      - nginx-proxy
      - letsencrypt
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: php
    ports:
      - 9000:9000
    volumes:
      - ./html:/var/www/html
      - ./logs:/var/log/nginx
    networks:
      - nginx-proxy
  
networks:
  nginx-proxy:
    external: true    