version: "3.1"
services:
	app:
		image: 'jc21/nginx-proxy-manager:latest'
		ports:
			- '8080:80'
			- '81:81'
			- '443:443'
		volumes:
			- ./config.json:/app/config/production.json
			- ./data:/data
			- ./letsencrypt:/etc/letsencrypt